[project]
name = "dinoflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "O'Fallon, Brendan", email = "brendan.o'fallon@aruplab.com" }
]
requires-python = "==3.12.*"
dependencies = [
    "comet-ml>=3.49.0",
    "ipython>=8.18.1",
    "numpy>=2.0",
    "pandas>=2.2.3",
    "scikit-learn",
    "scipy",
    "matplotlib>=3.9.4",
    "pytorch-lightning>=2.5.0.post0",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "torch>=2.6.0",
    "torchmetrics>=1.6.1",
    "typer",
    "torch-geometric>=2.6.1",
    "einops>=0.8.1",
]

[project.optional-dependencies]
som = [
    "jax[cuda12]>=0.5",
    "scikit-image>=0.24.0",
]
eval = [
    "ipykernel>=6.29.5",
    "altair>=5.5.0",
    "seaborn>=0.13.2",
    # "umap-learn>=0.5.7",  # requires something which requires python 3.10 only
]
geometric = [
    "torch-cluster @ https://data.pyg.org/whl/torch-2.7.0+cu128/torch_cluster-1.6.3%2Bpt27cu128-cp312-cp312-linux_x86_64.whl",
]

[project.scripts]
dinoflow = "dinoflow:main"

[build-system]
requires = ["hatchling", "torch>=2.6.0", "setuptools>=68.0.0"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
