[project]
name = "dinoflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "O'Fallon, Brendan", email = "brendan.o'fallon@aruplab.com" }
]
requires-python = ">=3.9"
dependencies = [
    "comet-ml>=3.49.0",
    "ipykernel>=6.29.5",
    "numpy>=2.0",
    "pandas>=2.2.3",
    "pytorch-lightning>=2.5.0.post0",
    "pyyaml>=6.0.2",
    "torch>=2.6.0",
    "torchmetrics>=1.6.1",
    "typer",
    "umap-learn",
]

[project.scripts]
dinoflow = "dinoflow:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
